const TINTUC = "TINTUC";
const BANNERS = "BANNERS";
const MENU = "MENU";
const KHAITHAC = "KHAITHAC";
const FOOTER = "FOOTER";

const CANHBAO = "CANHBAO";
const SOHUUTRITUE = "SOHUUTRITUE";

export { TINTUC, BANNERS, MENU, KHAITHAC, FOOTER, CANHBAO, SOHUUTRITUE };
